version: '3.8'

services:
  api:
    image: severancecalculator.api
    build:
      context: .
      dockerfile: SeveranceCalculator.API\Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  web:
    image: severancecalculator.web
    build:
      context: .
      dockerfile: SeveranceCalculator.Web\Dockerfile
    ports:
      - "9000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CalculatorApiHost=http://api:8080